### ISSUE TITLE
Swipe on card deck does not work on Android

### ISSUE THREAD

**Issue by Nicholas-Sliter** [csci0466-s22/project-codedash#7]

**Comment by Nicholas-Sliter** [comment]
https://github.com/facebook/react-native/issues/23836

**Comment by Nicholas-Sliter** [comment]
![image](https://user-images.githubusercontent.com/78503029/166163426-522aae4f-45de-48ef-9119-05334133963a.png)
After a bit of modification, its clear the Animated.View renders under the card, making it unusable.

**Comment by waynew99** [comment]
> ![image](https://user-images.githubusercontent.com/78503029/166163426-522aae4f-45de-48ef-9119-05334133963a.png) After a bit of modification, its clear the Animated.View renders under the card, making it unusable.

Ugh... That's why. Do you mind trying the new branch `cardDeckActions`? I modified the structure a bit to add more functionalities. It works on iOS, let's see if it works on Android.

**Comment by Nicholas-Sliter** [comment]
I partially solved it by removing the touchablewithoutfeedback and animated view from the card component

![image](https://user-images.githubusercontent.com/78503029/166163727-39ab5ddb-6a45-40e8-90b5-5c318366ac08.png)
![image](https://user-images.githubusercontent.com/78503029/166163730-ee8b92c4-dcef-4bdd-bd09-a7da5851d521.png)


![image](https://user-images.githubusercontent.com/78503029/166163738-a7e13c3e-2be9-4ecd-8782-87632de94058.png)

**Comment by Nicholas-Sliter** [comment]
That makes it fully interactable for me, but we lose the spring animation
